### ISSUE TITLE
Does not enforce HTTPS

### ISSUE THREAD

**Issue by piether** [thomaux/thomaux.github.io#1]
### Steps to reproduce

- Surf to [http://anc.io](http://anc.io)
- Look at the hideous slash through the padlock
![image](https://user-images.githubusercontent.com/295860/94447357-f404fb00-01a9-11eb-8b3a-ee4ea49fbe77.png)

### Solution

- Go to [https://github.com/thomaux/thomaux.github.io/settings](https://github.com/thomaux/thomaux.github.io/settings)
- Check the checkbox "Enforce HTTPS":

![image](https://user-images.githubusercontent.com/295860/94447117-bef8a880-01a9-11eb-807b-fd52f4782bd0.png)

**Comment by thomaux** [comment]
Fixed, thanks for reporting!
